config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  root 'welcome#index'

  get '/auth/:provider/callback', :to => 'sessions#create'

  get '/success', :to => 'welcome#success', :controller => 'welcome'

  get '/fetch', :to => 'welcome#fetch', :controller => 'welcome'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	  	auth_hash = request.env['omniauth.auth']
	  	session[:token] = auth_hash.credentials.token
	  	session[:secret] = auth_hash.credentials.secret
	  	session[:twitter_username] = auth_hash[:info][:name]
	  	redirect_to "/"
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  def index
  	
  end

  def success
  	@username = session[:twitter_username]
  end


  def fetch
  	begin
		client = Twitter::REST::Client.new do |config|
		  config.consumer_key        = ENV.fetch('FIND_THE_FOUNDER_CONSUMER_KEY')
		  config.consumer_secret     = ENV.fetch('FIND_THE_FOUNDER_CONSUMER_SECRET')
		  config.access_token        = session[:token]
	  	  config.access_token_secret = session[:secret]
	  	end
		
		# This will raise a 500 error

	  	followers = client.followers("gem")
	  	#puts followers[0]
		followers.each_slice(100) do |follower|
			puts follower
		end
	  	# No error was raised, create the list
	  	if @list.save
	      	redirect_to "/"
	    else
	      	render 'new'
	    end
	rescue Twitter::Error::NotFound => e
	    # if list is not found
	    redirect_to '/'
	end

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maker Feed | Find and follow fellow makers in just two clicks</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="https://i.imgur.com/X8BLrWY.png">
  <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono|Roboto:400,500,700" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-static-top" style=" border: none; background-color: white; margin-top: 10px; margin-left: 30px; margin-right: 30px; font-size: 16px;">
        <div class="container-fluid">
          <div class="navbar-header" style="margin-top: 10px;">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar" style="background-color: black;"></span>
              <span class="icon-bar" style="background-color: black;"></span>
              <span class="icon-bar" style="background-color: black;"></span>
            </button>
            <a style="color:#528B8B; font-size:18px;" href="/"><b>Fetch the Team Doggo</b></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
    
            <ul class="nav navbar-nav navbar-right">
              <li class="">
                <a style="color: grey;" href="/#how_does_it_work"> How Does It Work?</a>
              </li>
              <li class="">
                <a style="color: grey;" href="/#open_source"> Open Source</a>
              </li>
              <li class="">
                <a style="color: grey;" href="/#built_in_the_open"> Built in the Open</a>
              </li>
              <li class="">
                <a class="btn" style="border-color: #55acee; border-radius: 10px; border-width: 1.5px; font-size: 16px; color: grey;" href="/auth/twitter"> Sign Up with Twitter</a>
              </li>
            </ul>
          </div>
        </div>
      
</nav>

<%= yield %>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-119576122-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-119576122-1');
</script>

</body>
</html>

app/views/welcome/index.erb
<header>
  <div style=" background: url() ; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        height: 100vh;
        color: #fff;
        text-align: center;
        font-family: 'Roboto'">
    <img src="https://i.imgur.com/D89uCJC.png" style="height: 250px; margin-top: 50px;">
      <p style="font-size: 11px; color:grey; padding-top: 10px;">This is doggo. He is fucking cool, he can fetch anything. See for yourself</p>
      <p style="margin-top:30px; color:#528B8B; font-size: 50px;">Fetch the Team Doggo!</p>
      <p style="margin-bottom:30px; color: #696969; font-size: 18px;">Pass a company's twitter handle, doggo will fetch the team's and founder's twitter handles</p>
      <a target="_blank" href="https://github.com/alexandersideris/make-my-github-green" class="btn btn-default" style="border-radius: 10px; border-color: #424242; color: black; text-decoration: none; padding:10px; font-size: 16px; margin-right:10px; margin-bottom: 10px;"><span class="glyphicon glyphicon-eye-open"></span> View Code on GitHub</a>
      <a href="/auth/twitter" style="border-radius: 10px; color: white; text-decoration: none; padding:10px; font-size: 16px; margin-bottom: 10px;" class="btn btn-info"><span class="glyphicon glyphicon-user"></span> Sign Up with Twitter</a>
      
  </div>

</header>

<div id="how_does_it_work" style="text-align: center; font-family: 'Roboto'; margin-top: 80px;">

    <h2 style=" margin-bottom: 75px;">How does it work? 🤔</h2>

  <p style="font-size: 18px; margin:40px;"><span style="color:#2F4F4F;">1) </span>When you sign up, you will be taken to a page with twitter lists to select from</p>
  <p style="font-size: 18px; margin:40px;"><span style="color:#2F4F4F;">2) </span>Choose a list you find interesting, specify your criteria and hit 'Go'<br><span style="color:grey; font-size: 14px;">eg. 'find the 10 most active makers of indiehacker-community'</span></p>
  <p style="font-size: 18px; margin:40px;"><span style="color:#2F4F4F;">3) </span>View the users, you can either follow them or search again</p>




</div>

<div id="open_source" style="text-align: center; font-family: 'Roboto'">

  <h2 style="margin-top:100px; margin-bottom: 50px;">Open Source</h2>
  <div class="row">
    <div class="col col-md-2"></div>
    <div class="col col-md-8">
      <img src="https://i.imgur.com/0LpIAWJ.png" style="height:150px; margin:auto;"/>
    </div>
    <div class="col col-md-2">
    </div>
  </div>
  <a target="_blank" href="https://github.com/alexandersideris/follow-fellow-makers" class="btn btn-default" style="border-radius: 10px; border-color: #424242; color: black; text-decoration: none; padding:10px; font-size: 16px; margin-right:10px; margin-top: 40px;"><span class="glyphicon glyphicon-eye-open"></span> View Code on GitHub</a>
  <p style="font-size: 18px; margin:40px;">While building Maker Feed, I found that I needed full read and write access to the user's Twitter profile</p>
  <p style="font-size: 18px; margin:40px;">I understand that it might be too much to ask for, given that it is a very simple service</p>
  <p style="font-size: 18px; margin:40px;">In order to create a sense of security and show my pure intentions, I decided to open source it</p>

</div>

<div id="built_in_the_open" style="text-align: center; font-family: 'Roboto'; margin-bottom: 300px;">

  <h2 style="margin-top:100px; margin-bottom: 50px;">Built in the Open</h2>
  <div class="row">
    <div class="col col-md-2"></div>
    <div class="col col-md-8">
      <img src="https://i.imgur.com/MBIqgc9.png" style="height:150px; margin:auto;"/>
    </div>
    <div class="col col-md-2">
    </div>
  </div>
  <a target="_blank" href="https://twitter.com/alexsideris_/status/997158898665738243" class="btn btn-default" style="border-radius: 10px; border-color: #424242; color: black; text-decoration: none; padding:10px; font-size: 16px; margin-right:10px; margin-top: 40px;"><span class="glyphicon glyphicon-eye-open"></span> View Story on Twitter</a>
  <a target="_blank" href="https://wip.chat/products/1406" class="btn btn-default" style="border-radius: 10px; border-color: #424242; color: black; text-decoration: none; padding:10px; font-size: 16px; margin-right:10px; margin-top: 40px;"><span class="glyphicon glyphicon-eye-open"></span> View Progress on WIP</a>
  <p style="font-size: 18px; margin:40px;">The complete story, from idea conception to launch can be found on a single twitter thread</p>
  <p style="font-size: 18px; margin:40px;">You can also view all my public todos on WIP</p>

</div>

app/views/welcome/success.html.erb
<header>
  <div style=" background: url() ; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        height: 100vh;
        text-align: center;
        font-family: 'Roboto';
        margin-bottom: 300px;">
        <h2 style="color:#191919; margin-top: 100px;">You have successfully signed up for 'Fetch the Team Doggo' <%= @username.split(" ")[0] %>! 🎉</h2>
        <p style="color:grey; font-size: 19px; margin-bottom: 20px;">Enter a company's twitter handle and ask Doggo to fetch the team and founder for you 🔍</p>
        <input type="text" name="lname" placeholder="@twitter_handle"><br>
        <a href="/fetch" class="btn btn-success" style="margin:20px; padding:10px;">Fetch!</a>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<div class="container">

<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

</div>

app/views/widgets/index.html.erb
<div class="container">
<h1>Listing widgets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

</div>

app/views/widgets/new.html.erb
<div class="container">

<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

</div>

app/views/widgets/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>

</div>